language: python

python:
- 2.7
- 3.4
- 3.5
- 3.6

script:
- scripts/setup-dev.sh

before_install:
- pip install -U pip
- python setup.py install

script:
- scripts/tests.sh;
- scripts/tests-cli.sh

after_success:
- bash <(curl -s https://codecov.io/bash)

notifications:
  slack:
    secure: jRNXi8OwiiMdsY0rNuWLA194/NICXtljInimE1WiZYxGQ6PMU69X350QsVEs/eX8BpRw5KbFr3ssPf3I1cbtEIMWwUnWQ1M4gk/uGUQ2GIoYUwo9wX6fwH+R3Ooj7JFIZvHsGDVU6nwQM49Uq5BXJ8ce7WjXqThbPuLHHZgmfWPF3hySyOpp9KpqsR/ZnN02708Q4OR+DVlm75TsjVfyBiA61aUFYSpKn0k+AkpQp0/6F2jDrOJVUAbtNcXdY7tOCVjagpEQjy8R46y9BQF27Cqay/VS7zIsvbTDSb2L6fAdHuuigQx8pLC9VBWHDqkKBWbde/Rm6rwVW6LpXANg0+SRUbgBUL0rhRRJ/e7oas55aMRLmUKmTEhKt9kzl4QzksQbm2UJyOc0YxqqivMPxlHp/hKeOQ2Ald94iALJ1qCns3ZBZdbC8Eai6DLhimGywuzNAd7CSZyXQcI9sAnpd0UNZQQchB03VcuaaSm8hedzlztBy1EAReymKJiyWTZJEsm7jGIDsKtKLYVBjs6bq9r8ikRuU+bcX7tcL7XpVcW6qALBTD2yJZbqfcJohp/mJfptcXWDPxCihOyROTOH7l27kucUDQWGq5/xhZaPOQMC0Dv7X7QT54ytsNxT6rRPkmTO3djZIo6DKDA9dYBLbMGJvhrzbjtykoY21P3H+cM=
